import type { Metadata } from "next";
import "./globals.css";
import RoleRouteGuard from "@/components/RoleRouteGuard";

export const metadata: Metadata = {
  title: "心臓リハビリ手帳",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        {/* LIFF SDKを追加 */}
        <script src="https://static.line-scdn.net/liff/edge/2/sdk.js"></script>
      </head>
      <body className="p-4">
        <RoleRouteGuard />
        {children}
      </body>
    </html>
  );
}